baseURL = 'https://goncalomira.github.io/'
locale = 'pt-pt'
title = 'Gonçalo Mira'
theme = "hugo-theme-tokiwa"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
[[module.imports]]
  path = "github.com/heyeshuang/hugo-theme-tokiwa"